# -*- coding: utf-8 -*-
"""v.2_keyword_extractor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n8xakpCfrP_hVEBvM4i4pbti4Vc1eQbC

##接收日記內容並返回3-5個關鍵字
"""

# keyword_extractor.py (最終淨化版：只包含函式和必要的導入)

import json
import jieba.analyse
import os # <-- 新增：導入 os 模組

# ----------------------------------------------------
# 🌟 停用詞載入區塊 (正式加入) 🌟
# ----------------------------------------------------

# 設置絕對路徑：請確認這個路徑是您檔案在 Google Drive 上的確切位置
PROJECT_ROOT = '/content/drive/MyDrive/projects/LINE BOT'
STOPWORDS_FILE = os.path.join(PROJECT_ROOT, 'v2_stopwords_new.txt') # <-- 使用您確認正確的檔案名稱

if os.path.exists(STOPWORDS_FILE):
    try:
        # 這是唯一需要的函式：設置 Jieba 的停用詞檔案
        jieba.analyse.set_stop_words(STOPWORDS_FILE)
        # print(f"✅ Jieba 已成功載入停用詞表: {STOPWORDS_FILE}") # 可保留用於啟動時確認

    except Exception as e:
        # 這裡會捕捉到之前遇到的 'function' object has no attribute 'stop_words' 錯誤
        # 但由於 set_stop_words 已經成功，我們不需要擔心
        print(f"⚠️ 載入停用詞時發生例外，但可能已成功應用: {e}")
# ----------------------------------------------------


def extract_keywords_tfidf(text: str, topK: int = 5) -> str:
    """
    使用 Jieba 內建的 TF-IDF 算法提取中文關鍵詞。
    """
    if not text or len(text) < 5:
        return json.dumps([])

    try:
        # 核心變動：呼叫 jieba.analyse.extract_tags
        keywords_list = jieba.analyse.extract_tags(
            sentence=text,
            topK=topK,
            withWeight=False,
            allowPOS=('n', 'v', 'a')
        )

        if not keywords_list:
             return json.dumps([])

        return json.dumps(keywords_list, ensure_ascii=False)

    except Exception as e:
        print(f"Jieba TF-IDF 提取錯誤: {e}")
        return json.dumps([])

if __name__ == '__main__':
    # 執行單元測試
    test_diary = "今天工作上壓力很大，老闆突然叫我重做昨天晚上才交的簡報。雖然心情不太好，但晚餐吃了媽媽煮的紅燒肉，感覺好多了。希望明天可以順利完成專案。"

    keywords_json = extract_keywords_tfidf(test_diary, topK=4)

    print(f"測試日記：{test_diary}")
    print(f"提取結果：{keywords_json}")

    if keywords_json and keywords_json != '[]':
        print(f"解碼列表：{json.loads(keywords_json)}")